FROM node:18-alpine

WORKDIR /app

# Accept secrets as build args
ARG FIREBASE_API_KEY
ARG FIREBASE_SERVICE_ACCOUNT
ARG MAILERSEND_API_KEY
ARG APP_URL
ARG FIREBASE_REQUIRE_EMAIL_VERIFICATION
ARG MAILERSEND_FROM

# Export them into environment
ENV FIREBASE_API_KEY=$FIREBASE_API_KEY \
    FIREBASE_SERVICE_ACCOUNT=$FIREBASE_SERVICE_ACCOUNT \
    MAILERSEND_API_KEY=$MAILERSEND_API_KEY \
    APP_URL=$APP_URL \
    FIREBASE_REQUIRE_EMAIL_VERIFICATION=$FIREBASE_REQUIRE_EMAIL_VERIFICATION \
    MAILERSEND_FROM=$MAILERSEND_FROM

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "dev"]